# Generated by Django 6.1 on 2026-08-14 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('notional_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filled_qty', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('filled_avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('alpaca_order_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('filled', 'Filled'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('VOO', 'Vanguard S&P 500 ETF'), ('VTI', 'Vanguard Total Stock Market ETF'), ('QQQ', 'Invesco QQQ Trust'), ('AAPL', 'Apple Inc.'), ('MSFT', 'Microsoft Corp.'), ('TSLA', 'Tesla Inc.')], default='VOO', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invest_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
