from django.conf import settings
from django.db import models


class Transaction(models.Model):
    """A single bank transaction pulled from Plaid (or the fake client)."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="transactions"
    )
    bank_item = models.ForeignKey(
        "banking.BankItem", on_delete=models.CASCADE, related_name="transactions"
    )
    plaid_transaction_id = models.CharField(max_length=255, unique=True)
    merchant_name = models.CharField(max_length=255)
    category = models.CharField(max_length=100, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-date", "-id"]

    def __str__(self):
        return f"{self.merchant_name} ${self.amount}"


class RoundupLedgerEntry(models.Model):
    """The round-up generated by one transaction, and whether it has been
    swept into an investment order yet."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="roundup_entries"
    )
    transaction = models.OneToOneField(
        Transaction, on_delete=models.CASCADE, related_name="roundup_entry"
    )
    roundup_amount = models.DecimalField(max_digits=10, decimal_places=2)
    invested = models.BooleanField(default=False)
    investment_order = models.ForeignKey(
        "investing.InvestmentOrder",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="ledger_entries",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.email} +${self.roundup_amount} ({'invested' if self.invested else 'pending'})"
